In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from pylab import rcParams

# Set some Pandas options as you like
pd.set_option('max_columns', 30)
pd.set_option('max_rows', 30)

rcParams['figure.figsize'] = 15, 10
rcParams['font.size'] = 20

%matplotlib inline

## Merge Exercises:

**Exercise**: Read in the child_mortality_rates and adult_mortality_rates datasets and merge them on appropriate variables, using a meaningful merge technique. Perform data cleaning where necessary.

In [3]:
cm = pd.read_csv('../datasets/child_mortality_rates.csv')
cols = dict(zip(cm.columns, ['Country','Year','Data Source','Neonatal F','Neonatal M','Infant F','Infant M','U5 F','U5 M',]))
cm.rename(columns=cols, inplace=True)
cm.drop(0, inplace=True)
cm.head()

,Country,Year,Data Source,Neonatal F,Neonatal M,Infant F,Infant M,U5 F,U5 M
1,Albania,2008,DHS,8.4 [4.6-15.1],11.8 [7.0-20.1],15.5 [10.3-23.3],22.4 [15.9-31.6],16.1 [10.8-23.9],27.3 [20.2-36.9]
2,Armenia,2010,DHS,9.6 [5.1-18.0],9.3 [5.0-17.3],20.3 [12.4-33.1],17.0 [11.0-26.3],21.7 [13.6-34.5],21.3 [14.3-31.4]
3,Armenia,2005,DHS,15.5 [9.5-25.4],21.1 [13.5-33.0],25.5 [16.8-38.5],29.0 [20.2-41.4],28.5 [19.3-41.9],36.4 [26.4-49.8]
4,Armenia,2000,DHS,22.8 [15.9-32.8],28.5 [21.7-37.3],42.1 [32.7-54.1],45.3 [36.3-56.4],44.9 [35.3-56.9],50.1 [40.7-61.6]
5,Azerbaijan,2006,DHS,18.1 [11.4-28.8],37.0 [27.1-50.4],41.0 [31.3-53.7],54.9 [42.5-70.8],49.0 [38.1-62.7],64.3 [51.0-80.9]

In [4]:
def remove(x):
    if type(x) == str :
        if x.find(' ') == -1 :
            return x
        else : return x[0: x.find(' ')]    #[ : x.str.find(' ')]
    return x

In [5]:
def for_each_col(x):
    return x.apply(remove)

In [6]:
cm[cm.columns[3:]] = cm[cm.columns[3:]].apply(for_each_col)    
cm.head()

,Country,Year,Data Source,Neonatal F,Neonatal M,Infant F,Infant M,U5 F,U5 M
1,Albania,2008,DHS,8.4,11.8,15.5,22.4,16.1,27.3
2,Armenia,2010,DHS,9.6,9.3,20.3,17.0,21.7,21.3
3,Armenia,2005,DHS,15.5,21.1,25.5,29.0,28.5,36.4
4,Armenia,2000,DHS,22.8,28.5,42.1,45.3,44.9,50.1
5,Azerbaijan,2006,DHS,18.1,37.0,41.0,54.9,49.0,64.3

In [7]:
am = pd.read_csv('../datasets/adult_mortality_rates.csv')
am.rename(columns=am.iloc[0], inplace=True)
am.drop(0, inplace=True)

In [8]:
am.head()

       Country  Year  Both sexes  Female  Male
1  Afghanistan  2013         242     232   252
2  Afghanistan  2012         268     242   294
3  Afghanistan  2000         325     301   349
4  Afghanistan  1990         389     368   412
5      Albania  2013         102      85   118

In [9]:
cmam = pd.merge(cm, am, left_on=['Country','Year'], right_on=['Country','Year'])
cmam.head()

,Country,Year,Data Source,Neonatal F,Neonatal M,Infant F,Infant M,U5 F,U5 M,Both sexes,Female,Male
0,Armenia,2000,DHS,22.8,28.5,42.1,45.3,44.9,50.1,149,96,210
1,Cambodia,2000,DHS,34.1,43.9,82.3,102.9,109.9,132.4,271,240,307
2,Colombia,2000,DHS,13.0,19.4,20.2,28.4,23.5,32.3,163,100,225
3,Comoros,2012,DHS,22.9,27.6,37.4,39.1,51.8,47.8,260,236,283
4,Democratic Republic of the Congo,2013,DHS,28.1,32.3,62.7,66.9,108.1,113.9,349,320,379

**Exercise**: Generate several plots on the above data. Is there anything interesting?

**Exercise**: Read in the adult_mortality_rate_by_cause dataset and merge it with the above dataset on appropriate variables, using a meaningful merge technique.

In [10]:
amc = pd.read_csv('../datasets/adult_mortality_rate_by_cause.csv')
amc.rename(columns=amc.iloc[0], inplace=True)
amc.drop(0, inplace=True)
amc.rename(columns={u' Communicable &amp; other Group I' : 'Communicable/Group I'}, inplace=True)
amc.head()

,Country,Year,All Causes,Communicable/Group I,Noncommunicable diseases,Injuries
1,Afghanistan,2012,1378.2,362.7,846.3,169.2
2,Afghanistan,2000,1660.5,574.8,905.5,180.2
3,Albania,2012,766.1,46.5,671.6,48
4,Albania,2000,986.5,75.4,840,71.1
5,Algeria,2012,862,97.8,710.4,53.8

In [11]:
all_df = pd.merge(cmam, amc, left_on=['Country','Year'], right_on=['Country','Year'])
all_df.head()

,Country,Year,Data Source,Neonatal F,Neonatal M,Infant F,Infant M,U5 F,U5 M,Both sexes,Female,Male,All Causes,Communicable/Group I,Noncommunicable diseases,Injuries
0,Armenia,2000,DHS,22.8,28.5,42.1,45.3,44.9,50.1,149,96,210,837.2,51.8,745.8,39.5
1,Cambodia,2000,DHS,34.1,43.9,82.3,102.9,109.9,132.4,271,240,307,1107.2,544.2,472.3,90.6
2,Colombia,2000,DHS,13.0,19.4,20.2,28.4,23.5,32.3,163,100,225,645.7,73.9,434.3,137.5
3,Comoros,2012,DHS,22.9,27.6,37.4,39.1,51.8,47.8,260,236,283,1322.5,494.6,695.5,132.4
4,Egypt,2000,DHS,25.2,32.5,54.2,55.1,69.3,68.6,177,136,218,995.3,121,838.3,36.1

**Exercise**: Finally, read in the total_health_expenditure_by_country_per_year dataset. Attempt to merge it with the above dataset. What are the challenges? How might you work around them?

In [12]:
th = pd.read_csv('../datasets/total_health_expenditure_peercent_per_capita_of_gdp_by_country_per_year.csv')
th.head()

       Country  2013  2012  2000
0  Afghanistan   8.1   8.5   NaN
1      Albania   5.9   5.6   6.3
2      Algeria   6.6   6.0   3.5
3      Andorra   8.1   8.3   6.0
4       Angola   3.8   3.5   3.4

In [13]:
thm = pd.melt(th, ['Country'], ['2013','2012', '2000'],var_name='Year', value_name='HealthExpPercPerCapitaOfGDP').sort_values('Country')
thm.head()

         Country  Year  HealthExpPercPerCapitaOfGDP
0    Afghanistan  2013                          8.1
191  Afghanistan  2012                          8.5
382  Afghanistan  2000                          NaN
1        Albania  2013                          5.9
192      Albania  2012                          5.6

In [14]:
all2_df = pd.merge(all_df, thm, left_on=['Country','Year'], right_on=['Country','Year'])
all2_df.head()

,Country,Year,Data Source,Neonatal F,Neonatal M,Infant F,Infant M,U5 F,U5 M,Both sexes,Female,Male,All Causes,Communicable/Group I,Noncommunicable diseases,Injuries,HealthExpPercPerCapitaOfGDP
0,Armenia,2000,DHS,22.8,28.5,42.1,45.3,44.9,50.1,149,96,210,837.2,51.8,745.8,39.5,6.3
1,Cambodia,2000,DHS,34.1,43.9,82.3,102.9,109.9,132.4,271,240,307,1107.2,544.2,472.3,90.6,5.8
2,Colombia,2000,DHS,13.0,19.4,20.2,28.4,23.5,32.3,163,100,225,645.7,73.9,434.3,137.5,5.9
3,Comoros,2012,DHS,22.9,27.6,37.4,39.1,51.8,47.8,260,236,283,1322.5,494.6,695.5,132.4,6.5
4,Egypt,2000,DHS,25.2,32.5,54.2,55.1,69.3,68.6,177,136,218,995.3,121,838.3,36.1,5.4

---